package test

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestGeneratorFixtures(t *testing.T) {
	t.Parallel()

	if _, err := exec.LookPath("protoc"); err != nil {
		t.Skip("protoc not installed")
	}

	rootDir := repoRoot(t)
	fixtureDir := filepath.Join(rootDir, "test")
	includeDir := protocIncludeDir(t)
	workDir := t.TempDir()
	pluginPath := filepath.Join(workDir, "protoc-gen-sol")
	outDir := filepath.Join(workDir, "generated")
	inlineOutDir := filepath.Join(workDir, "generated-inline")

	buildCmd := exec.Command("go", "build", "-o", pluginPath, ".")
	buildCmd.Dir = rootDir
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("build plugin: %v\n%s", err, out)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("create output dir: %v", err)
	}
	if err := os.MkdirAll(inlineOutDir, 0o755); err != nil {
		t.Fatalf("create inline output dir: %v", err)
	}

	cmd := exec.Command(
		"protoc",
		"--plugin=protoc-gen-sol="+pluginPath,
		"--proto_path="+fixtureDir,
		"--proto_path="+includeDir,
		"--sol_out=importpb=true:"+outDir,
		"test.proto",
		"a.proto",
		"b.proto",
	)
	cmd.Dir = fixtureDir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("run protoc: %v\n%s", err, out)
	}

	inlineCmd := exec.Command(
		"protoc",
		"--plugin=protoc-gen-sol="+pluginPath,
		"--proto_path="+fixtureDir,
		"--proto_path="+includeDir,
		"--sol_out=importpb=false:"+inlineOutDir,
		"test.proto",
		"a.proto",
		"b.proto",
	)
	inlineCmd.Dir = fixtureDir
	if out, err := inlineCmd.CombinedOutput(); err != nil {
		t.Fatalf("run protoc inline runtime: %v\n%s", err, out)
	}

	for _, name := range []string{"Pb.sol", "PbMytest.sol", "PbA.sol", "PbB.sol"} {
		if _, err := os.Stat(filepath.Join(outDir, name)); err != nil {
			t.Fatalf("expected generated file %s: %v", name, err)
		}
	}

	pbRuntime := readFile(t, filepath.Join(outDir, "Pb.sol"))
	for _, want := range []string{
		"// SPDX-License-Identifier: MIT",
		"// Code generated by protoc-gen-sol. DO NOT EDIT.",
		"pragma solidity >=0.8.0;",
		"Provides the `Buffer` cursor type and primitive decode helpers used by",
		"if (tag > 0 && tag <= maxtag) {",
		"require(idx < len);",
		"require(b.length <= 32);",
	} {
		if !strings.Contains(pbRuntime, want) {
			t.Fatalf("expected Pb.sol to contain %q", want)
		}
	}
	if strings.Contains(pbRuntime, "require(raw.length > 1);") {
		t.Fatalf("did not expect legacy runtime guard in Pb.sol")
	}
	if !strings.Contains(pbRuntime, "require(b.length == 20);") {
		t.Fatalf("expected address length guard in Pb.sol")
	}

	pbMytest := readFile(t, filepath.Join(outDir, "PbMytest.sol"))
	for _, want := range []string{
		"// SPDX-License-Identifier: MIT",
		"// source: test.proto",
		"pragma solidity >=0.8.0;",
		"@title PbMytest",
		"**Auto-generated.** Solidity decoders for the protobuf messages defined in",
		"regenerate via `pb3-gen-sol`.",
		"address payable addrPayable;",
		"address payable[] addrPayables;",
		"uint ts;",
		"uint[] tss;",
		"uint256[] memory cnts = buf.cntTags(12);",
		"m.f4 = buf.decBytes();",
		"m.ts = buf.decVarint();",
	} {
		if !strings.Contains(pbMytest, want) {
			t.Fatalf("expected PbMytest.sol to contain %q", want)
		}
	}
	if strings.Contains(pbMytest, "if (false) {} // solidity has no switch/case") {
		t.Fatalf("did not expect legacy dispatch sentinel in PbMytest.sol")
	}
	if strings.Contains(pbMytest, "pragma solidity ^0.5.0;") {
		t.Fatalf("did not expect legacy pragma in PbMytest.sol")
	}

	if _, err := os.Stat(filepath.Join(inlineOutDir, "Pb.sol")); !os.IsNotExist(err) {
		t.Fatalf("did not expect standalone Pb.sol for importpb=false, got err=%v", err)
	}

	inlinePbMytest := readFile(t, filepath.Join(inlineOutDir, "PbMytest.sol"))
	for _, want := range []string{
		"library Pb {",
		"Provides the `Buffer` cursor type and primitive decode helpers used by",
		"assembly (\"memory-safe\") {",
	} {
		if !strings.Contains(inlinePbMytest, want) {
			t.Fatalf("expected inline PbMytest.sol to contain %q", want)
		}
	}
	if strings.Contains(inlinePbMytest, `import "./Pb.sol";`) {
		t.Fatalf("did not expect Pb.sol import for importpb=false")
	}
	if got := strings.Count(inlinePbMytest, "// SPDX-License-Identifier: MIT"); got != 1 {
		t.Fatalf("expected one SPDX header in inline PbMytest.sol, got %d", got)
	}
	if got := strings.Count(inlinePbMytest, "// Code generated by protoc-gen-sol. DO NOT EDIT."); got != 1 {
		t.Fatalf("expected one generated header in inline PbMytest.sol, got %d", got)
	}
	if got := strings.Count(inlinePbMytest, "pragma solidity >=0.8.0;"); got != 1 {
		t.Fatalf("expected one pragma in inline PbMytest.sol, got %d", got)
	}
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve repo root")
	}
	return filepath.Dir(filepath.Dir(file))
}

func protocIncludeDir(t *testing.T) string {
	t.Helper()

	protocPath, err := exec.LookPath("protoc")
	if err != nil {
		t.Fatalf("look up protoc: %v", err)
	}

	candidates := []string{
		filepath.Join(filepath.Dir(filepath.Dir(protocPath)), "include"),
		"/usr/local/include",
		"/opt/homebrew/include",
	}
	for _, dir := range candidates {
		if _, err := os.Stat(filepath.Join(dir, "google", "protobuf", "descriptor.proto")); err == nil {
			return dir
		}
	}

	t.Fatalf("could not locate protobuf include directory for descriptor.proto")
	return ""
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}
