// SPDX-License-Identifier: MIT
// Code generated by protoc-gen-sol. DO NOT EDIT.
pragma solidity >=0.8.0;

/**
 * @title Pb
 * @notice Runtime support library for Solidity protobuf decoders generated by
 *  `pb3-gen-sol`. Provides the `Buffer` cursor type and primitive decode helpers used by
 *  generated `Pb*` decoder libraries.
 */
library Pb {
    enum WireType {
        Varint,
        Fixed64,
        LengthDelim,
        StartGroup,
        EndGroup,
        Fixed32
    }

    struct Buffer {
        uint256 idx; // the start index of next read. when idx=b.length, we're done
        bytes b; // hold serialized proto msg, readonly
    }

    // create a new in-memory Buffer object from raw msg bytes
    function fromBytes(bytes memory raw) internal pure returns (Buffer memory buf) {
        buf.b = raw;
        buf.idx = 0;
    }

    // whether there are unread bytes
    function hasMore(Buffer memory buf) internal pure returns (bool) {
        return buf.idx < buf.b.length;
    }

    // decode current field number and wiretype
    function decKey(Buffer memory buf) internal pure returns (uint256 tag, WireType wiretype) {
        uint256 v = decVarint(buf);
        tag = v / 8;
        wiretype = WireType(v & 7);
    }

    // count tag occurrences, return an array due to no memory map support
    // have to create array for (maxtag+1) size. cnts[tag] = occurrences
    // should keep buf.idx unchanged because this is only a count function
    function cntTags(Buffer memory buf, uint256 maxtag) internal pure returns (uint256[] memory cnts) {
        uint256 originalIdx = buf.idx;
        cnts = new uint256[](maxtag + 1); // protobuf's tags are from 1 rather than 0
        uint256 tag;
        WireType wire;
        while (hasMore(buf)) {
            (tag, wire) = decKey(buf);
            if (tag > 0 && tag <= maxtag) {
                // Per-tag count is bounded by payload length, which is bounded
                // by gas — overflow is unreachable.
                unchecked {
                    cnts[tag] += 1;
                }
            }
            skipValue(buf, wire);
        }
        buf.idx = originalIdx;
    }

    // read varint from current buf idx, move buf.idx to next read, return the int value
    function decVarint(Buffer memory buf) internal pure returns (uint256 v) {
        bytes memory bb = buf.b;
        uint256 idx = buf.idx;
        uint256 len = bb.length;
        // Cache the bytes data pointer once. Solidity's `bb[idx]` would re-derive
        // it and run an implicit bounds check every iteration; the inline mload
        // plus explicit `idx < len` check below is the same safety with less per-
        // byte overhead.
        uint256 dataPtr;
        assembly ("memory-safe") {
            dataPtr := add(bb, 32)
        }
        // The loop is wrapped in `unchecked` because every arithmetic op inside
        // is bounded: `i` runs 0..9, `idx` is bounded by `len` via the require,
        // and `(i * 7)` peaks at 63. The explicit `require(idx < len)` retains
        // the truncation revert.
        unchecked {
            for (uint256 i = 0; i < 10; ++i) {
                require(idx < len);
                uint256 b;
                assembly ("memory-safe") {
                    // mload reads 32 bytes; we only consume byte 0 (idx itself), and
                    // idx < len guarantees that byte is within the buffer. Bytes 1..31
                    // may sit past the buffer's data but are never used.
                    b := byte(0, mload(add(dataPtr, idx)))
                }
                idx++;
                v |= (b & 0x7F) << (i * 7);
                if (b < 0x80) {
                    buf.idx = idx;
                    return v;
                }
            }
        }
        revert(); // i=10, invalid varint stream
    }

    // read length delimited field and return bytes
    function decBytes(Buffer memory buf) internal pure returns (bytes memory b) {
        uint256 len = decVarint(buf);
        uint256 end = buf.idx + len;
        require(end <= buf.b.length); // avoid overflow
        b = new bytes(len);
        bytes memory bufB = buf.b; // get buf.b mem addr to use in assembly
        uint256 bStart;
        uint256 bufBStart = buf.idx;
        assembly ("memory-safe") {
            bStart := add(b, 32)
            bufBStart := add(add(bufB, 32), bufBStart)
        }
        // i is bounded by len (≤ payload size); the trailing partial-word write
        // stays within `b`'s 32-byte-padded allocation. unchecked is safe.
        for (uint256 i = 0; i < len;) {
            assembly ("memory-safe") {
                mstore(add(bStart, i), mload(add(bufBStart, i)))
            }
            unchecked {
                i += 32;
            }
        }
        buf.idx = end;
    }

    // return packed ints
    function decPacked(Buffer memory buf) internal pure returns (uint256[] memory t) {
        uint256 len = decVarint(buf);
        uint256 end = buf.idx + len;
        require(end <= buf.b.length); // avoid overflow
        // array in memory must be init w/ known length, so allocate the max
        // possible element count first and then shrink the final length in place.
        t = new uint256[](len);
        uint256 i = 0; // count how many ints are there
        while (buf.idx < end) {
            t[i] = decVarint(buf);
            unchecked {
                i++;
            }
        }
        assembly ("memory-safe") {
            mstore(t, i)
        }
    }

    // move idx pass current value field, to beginning of next tag or msg end
    function skipValue(Buffer memory buf, WireType wire) internal pure {
        if (wire == WireType.Varint) {
            decVarint(buf);
        } else if (wire == WireType.LengthDelim) {
            uint256 len = decVarint(buf);
            buf.idx += len; // skip len bytes value data
            require(buf.idx <= buf.b.length); // avoid overflow
        } else {
            revert(); // unsupported wiretype
        }
    }

    // type conversion help utils
    function _bool(uint256 x) internal pure returns (bool v) {
        return x != 0;
    }

    // Fixed-width length-delimited readers. Each one reads its own varint
    // length prefix from `buf`, validates the length, mloads the payload
    // directly into the target type, and advances `buf.idx`. Saves the
    // intermediate `bytes` allocation that `decBytes` + a helper conversion
    // would otherwise pay.

    // Read a length-delimited field of exactly 20 bytes as an address.
    // Returns `address payable` so the same call can be used for both
    // `address` and `address payable` schema fields (Solidity allows the
    // implicit `address payable` → `address` direction on assignment).
    function decAddress(Buffer memory buf) internal pure returns (address payable v) {
        uint256 len = decVarint(buf);
        require(len == 20);
        uint256 idx = buf.idx;
        require(idx + 20 <= buf.b.length);
        bytes memory bb = buf.b;
        assembly ("memory-safe") {
            // address occupies the high-order 20 bytes of the loaded word; shr
            // by 96 bits drops the trailing 12 bytes of (possibly past-buffer)
            // memory which are never used.
            v := shr(96, mload(add(add(bb, 32), idx)))
        }
        buf.idx = idx + 20;
    }

    // Read a length-delimited field of exactly 32 bytes as bytes32.
    function decBytes32(Buffer memory buf) internal pure returns (bytes32 v) {
        uint256 len = decVarint(buf);
        require(len == 32);
        uint256 idx = buf.idx;
        require(idx + 32 <= buf.b.length);
        bytes memory bb = buf.b;
        assembly ("memory-safe") {
            v := mload(add(add(bb, 32), idx))
        }
        buf.idx = idx + 32;
    }

    // Read a length-delimited field of <= 32 bytes as a big-endian uint256.
    // This mirrors the existing soltype="uint256" wire shape: leading-zero
    // bytes are stripped on the wire, so we right-shift the loaded word by
    // (32 - len) bytes to align the value into the low-order bits.
    function decUint256(Buffer memory buf) internal pure returns (uint256 v) {
        uint256 len = decVarint(buf);
        require(len <= 32);
        uint256 idx = buf.idx;
        uint256 end = idx + len;
        require(end <= buf.b.length);
        bytes memory bb = buf.b;
        // For len == 0 the EVM `shr` opcode returns 0 (shift >= 256 is
        // defined as zero). buf.idx is unchanged in that case, which matches
        // the proto3 default-zero semantics for an empty bytes field.
        assembly ("memory-safe") {
            v := shr(mul(sub(32, len), 8), mload(add(add(bb, 32), idx)))
        }
        buf.idx = end;
    }

    // uint[] to uint8[]
    function uint8s(uint256[] memory arr) internal pure returns (uint8[] memory t) {
        uint256 n = arr.length;
        t = new uint8[](n);
        for (uint256 i = 0; i < n;) {
            t[i] = uint8(arr[i]);
            unchecked {
                ++i;
            }
        }
    }

    function uint32s(uint256[] memory arr) internal pure returns (uint32[] memory t) {
        uint256 n = arr.length;
        t = new uint32[](n);
        for (uint256 i = 0; i < n;) {
            t[i] = uint32(arr[i]);
            unchecked {
                ++i;
            }
        }
    }

    function uint64s(uint256[] memory arr) internal pure returns (uint64[] memory t) {
        uint256 n = arr.length;
        t = new uint64[](n);
        for (uint256 i = 0; i < n;) {
            t[i] = uint64(arr[i]);
            unchecked {
                ++i;
            }
        }
    }

    function bools(uint256[] memory arr) internal pure returns (bool[] memory t) {
        uint256 n = arr.length;
        t = new bool[](n);
        for (uint256 i = 0; i < n;) {
            t[i] = arr[i] != 0;
            unchecked {
                ++i;
            }
        }
    }
}