// SPDX-License-Identifier: MIT
// Code generated by protoc-gen-sol. DO NOT EDIT.
// source: b.proto
pragma solidity >=0.8.0;

import "./Pb.sol";
import "./PbA.sol";

/**
 * @title PbB
 * @notice **Auto-generated.** Solidity decoders for the protobuf messages defined in
 *  `b.proto`. Do not hand-edit this file; change the proto schema and
 *  regenerate via `pb3-gen-sol`.
 */
library PbB {
    using Pb for Pb.Buffer; // so we can call Pb funcs on Buffer obj

    struct B {
        PbA.A i; // tag: 1
        PbA.A[] alist; // tag: 2
        PbA.MyEnum e; // tag: 3
        PbA.MyEnum[] elist; // tag: 4
    } // end struct B

    function decB(bytes memory raw) internal pure returns (B memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.i = PbA.decA(buf.decBytes());
            } else if (key == 18) {
                // tag 2
                PbA.A memory _v2 = PbA.decA(buf.decBytes());
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else if (key == 24) {
                // tag 3
                m.e = PbA.MyEnum(buf.decVarint());
            } else if (key == 34) {
                // tag 4
                m.elist = PbA.MyEnums(buf.decPacked());
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        PbA.A[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.alist = _result2;
    } // end decoder B
}
