// SPDX-License-Identifier: MIT
// Code generated by protoc-gen-sol. DO NOT EDIT.
// source: chain.proto
pragma solidity >=0.8.0;

import "./Pb.sol";

/**
 * @title PbChain
 * @notice **Auto-generated.** Solidity decoders for the protobuf messages defined in
 *  `chain.proto`. Do not hand-edit this file; change the proto schema and
 *  regenerate via `pb3-gen-sol`.
 */
library PbChain {
    using Pb for Pb.Buffer; // so we can call Pb funcs on Buffer obj

    struct OpenChannelRequest {
        bytes channelInitializer; // tag: 1
        bytes[] sigs; // tag: 2
    } // end struct OpenChannelRequest

    function decOpenChannelRequest(bytes memory raw) internal pure returns (OpenChannelRequest memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.channelInitializer = buf.decBytes();
            } else if (key == 18) {
                // tag 2
                bytes memory _v2 = buf.decBytes();
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        bytes[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.sigs = _result2;
    } // end decoder OpenChannelRequest

    struct CooperativeWithdrawRequest {
        bytes withdrawInfo; // tag: 1
        bytes[] sigs; // tag: 2
    } // end struct CooperativeWithdrawRequest

    function decCooperativeWithdrawRequest(bytes memory raw)
        internal
        pure
        returns (CooperativeWithdrawRequest memory m)
    {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.withdrawInfo = buf.decBytes();
            } else if (key == 18) {
                // tag 2
                bytes memory _v2 = buf.decBytes();
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        bytes[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.sigs = _result2;
    } // end decoder CooperativeWithdrawRequest

    struct CooperativeSettleRequest {
        bytes settleInfo; // tag: 1
        bytes[] sigs; // tag: 2
    } // end struct CooperativeSettleRequest

    function decCooperativeSettleRequest(bytes memory raw) internal pure returns (CooperativeSettleRequest memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.settleInfo = buf.decBytes();
            } else if (key == 18) {
                // tag 2
                bytes memory _v2 = buf.decBytes();
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        bytes[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.sigs = _result2;
    } // end decoder CooperativeSettleRequest

    struct ResolvePayByConditionsRequest {
        bytes condPay; // tag: 1
        bytes[] hashPreimages; // tag: 2
    } // end struct ResolvePayByConditionsRequest

    function decResolvePayByConditionsRequest(bytes memory raw)
        internal
        pure
        returns (ResolvePayByConditionsRequest memory m)
    {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.condPay = buf.decBytes();
            } else if (key == 18) {
                // tag 2
                bytes memory _v2 = buf.decBytes();
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        bytes[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.hashPreimages = _result2;
    } // end decoder ResolvePayByConditionsRequest

    struct SignedSimplexState {
        bytes simplexState; // tag: 1
        bytes[] sigs; // tag: 2
    } // end struct SignedSimplexState

    function decSignedSimplexState(bytes memory raw) internal pure returns (SignedSimplexState memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.simplexState = buf.decBytes();
            } else if (key == 18) {
                // tag 2
                bytes memory _v2 = buf.decBytes();
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        bytes[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.sigs = _result2;
    } // end decoder SignedSimplexState

    struct SignedSimplexStateArray {
        SignedSimplexState[] signedSimplexStates; // tag: 1
    } // end struct SignedSimplexStateArray

    function decSignedSimplexStateArray(bytes memory raw) internal pure returns (SignedSimplexStateArray memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr1 = new uint256[](raw.length / 2);
        uint256 _cnt1 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                SignedSimplexState memory _v1 = decSignedSimplexState(buf.decBytes());
                assembly ("memory-safe") { mstore(add(add(_arr1, 32), shl(5, _cnt1)), _v1) }
                unchecked {
                    _cnt1++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        SignedSimplexState[] memory _result1;
        assembly ("memory-safe") {
            mstore(_arr1, _cnt1)
            _result1 := _arr1
        }
        m.signedSimplexStates = _result1;
    } // end decoder SignedSimplexStateArray

    struct ChannelMigrationRequest {
        bytes channelMigrationInfo; // tag: 1
        bytes[] sigs; // tag: 2
    } // end struct ChannelMigrationRequest

    function decChannelMigrationRequest(bytes memory raw) internal pure returns (ChannelMigrationRequest memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory _arr2 = new uint256[](raw.length / 2);
        uint256 _cnt2 = 0;

        uint256 key;
        while (buf.hasMore()) {
            key = buf.decVarint();
            if (key == 10) {
                // tag 1
                m.channelMigrationInfo = buf.decBytes();
            } else if (key == 18) {
                // tag 2
                bytes memory _v2 = buf.decBytes();
                assembly ("memory-safe") { mstore(add(add(_arr2, 32), shl(5, _cnt2)), _v2) }
                unchecked {
                    _cnt2++;
                }
            } else {
                buf.skipValue(Pb.WireType(key & 7)); // unknown tag or wrong wire
            }
        }

        bytes[] memory _result2;
        assembly ("memory-safe") {
            mstore(_arr2, _cnt2)
            _result2 := _arr2
        }
        m.sigs = _result2;
    } // end decoder ChannelMigrationRequest
}
