// SPDX-License-Identifier: MIT
// Code generated by protoc-gen-sol. DO NOT EDIT.
// source: b.proto
pragma solidity >=0.8.0;

import "./Pb.sol";
import "./PbA.sol";

/**
 * @title PbB
 * @notice **Auto-generated.** Solidity decoders for the protobuf messages defined in
 *  `b.proto`. Do not hand-edit this file; change the proto schema and
 *  regenerate via `pb3-gen-sol`.
 */
library PbB {
    using Pb for Pb.Buffer; // so we can call Pb funcs on Buffer obj

    struct B {
        PbA.A i; // tag: 1
        PbA.A[] alist; // tag: 2
        PbA.MyEnum e; // tag: 3
        PbA.MyEnum[] elist; // tag: 4
    } // end struct B

    function decB(bytes memory raw) internal pure returns (B memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory cnts = buf.cntTags(4);
        m.alist = new PbA.A[](cnts[2]);
        cnts[2] = 0; // reset counter for later use

        uint256 tag;
        Pb.WireType wire;
        while (buf.hasMore()) {
            (tag, wire) = buf.decKey();
            if (tag == 1) {
                m.i = PbA.decA(buf.decBytes());
            } else if (tag == 2) {
                m.alist[cnts[2]] = PbA.decA(buf.decBytes());
                unchecked {
                    cnts[2]++;
                }
            } else if (tag == 3) {
                m.e = PbA.MyEnum(buf.decVarint());
            } else if (tag == 4) {
                m.elist = PbA.MyEnums(buf.decPacked());
            } else {
                buf.skipValue(wire); // skip value of unknown tag
            }
        }
    } // end decoder B
}
